version: '3.4'
services:
   db:
     image: trocadeiro/mysql-restwithspringboot
     command: mysqld --default-authentication-plugin=mysql_native_password
     restart: always
     build:
       context: .
       dockerfile: Dockerfile
     environment:
       TZ: America/Sao_Paulo
       MYSQL_ROOT_PASSWORD: docker
       MYSQL_USER: docker
       MYSQL_PASSWORD: docker
       MYSQL_DATABASE: restwithspringboot
     ports:
       - "3308:3306"
     networks:
       - udemy-network
   rest-with-springboot-calculadora:
     image: trocadeiro/rest-with-springboot-calculadora
     restart: always
     build: ./rest-with-springboot-calculadora
     working_dir: /rest-with-springboot-calculadora
     environment:
       TZ: America/Sao_Paulo
       SPRING_BOOT_ENVIRONMENT: Production
     volumes:
       - ./rest-with-springboot-calculadora:/rest-with-springboot-calculadora
       - ~/.m2:/root/.m2
     ports:
       - "8080:8080"
     command: mvn clean spring-boot:run
     links:
       - db
     depends_on:
       - db
     networks:
       - udemy-network
networks:
    udemy-network:
        driver: bridge
        